services:
  # Serviço da aplicação Node.js
  app:
    env_file: ".env"
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - postgres
      - mongodb
    environment:
      - NODE_ENV=development
      - PORT=3000
      - DB_HOST=${POSTGRES_DB}
      - DB_PORT=5432
      - DB_NAME=${POSTGRES_DB}
      - DB_USER=${POSTGRES_USER}
      - DB_PASSWORD=${POSTGRES_PASSWORD}
      - MONGODB_URI=mongodb://mongodb:27017/blog_api
      - JWT_SECRET=seu_jwt_secret_aqui
      - JWT_EXPIRATION=1h
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules

  # Serviço PostgreSQL
  postgres:
    env_file: ".env"
    container_name: ${POSTGRES_DB}
    image: postgres:17
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  # Serviço MongoDB
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

# Definição dos volumes
volumes:
  postgres_data:
  mongodb_data:
